### ISSUE TITLE
its show some error ,while running cam is closing fast

### ISSUE THREAD

**Issue by Abhinchand** [trygvea/face-recognition-dlib#2]

**Comment by Abhinchand** [comment]
Traceback (most recent call last):
  File "face_recognition.py", line 112, in <module>
    recognize_faces_in_video(face_encodings, person_names)
  File "face_recognition.py", line 99, in recognize_faces_in_video
    match = find_match(face_encodings, person_names, face_encodings_in_image[0])
  File "face_recognition.py", line 27, in find_match
    matches = get_face_matches(known_faces, face) # get a list of True/False
  File "face_recognition.py", line 23, in get_face_matches
    return np.linalg.norm(known_faces - face, axis=1)
ValueError: operands could not be broadcast together with shapes (0,) (128,)
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by krshashank963** [comment]
I think you are not releasing videocapture() so usse
camera.release()
cv2.destroyAllWindows()

Hopefully it will work
